site_name: Maas Wiki NRW Demo
theme:
  name: material
  custom_dir: material/overrides
  palette:
    primary: custom
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: 'https://github.com/PartTimeDataScientist/mkdocs-wiki-test'

  analytics: 
    feedback:
      title: War die Seite hilfreich?
      ratings:
        - icon: material/emoticon-happy-outline
          name: Diese Seite ist super!
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: Hier gibt es was zu verbessern!
          data: 0
          note: >- 
            Danke für das Feedback! <a href="https://github.com/PartTimeDataScientist/mkdocs-wiki-test/issues/new/?title=[Feedback]+-+{title}+-+{url}" target="_blank">Sag uns gerne, was wir verbessern können!</a>

extra_css:
  - 'stylesheets/extra.css'

extra_javascript:
  - javascripts/feedback.js

repo_name: 'PartTimeDataScientist/mkdocs-cms'
repo_url: 'https://github.com/PartTimeDataScientist/mkdocs-wiki-test'
edit_uri: blob/master/docs/

# Plugins
plugins:
  - search
  - awesome-pages
# Extensions
markdown_extensions:
  - toc:
      permalink: "#"
  - smarty
  - admonition
  - footnotes
  - codehilite
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - fontawesome_markdown
# Page tree
#nav:
#  - 'Maas Wiki NRW': 'index.md'
#  - '"Wiki"-Benutzung': 'how-to.md'
#  - 'Einführung':
#    - Start: 'introduction/index.md'
#  - Maas-Baukasten:
#    - 'MaaS-Baukasten': 'examples/index.md'
#  - Erweiterungen: 'extensions/*'
#    - 'Admonition': 'extensions/admonition.md'
    #- 'CodeHilite': 'extensions/codehilite.md'
    #- 'Footnotes': 'extensions/footnotes.md'
    #- 'Metadata': 'extensions/metadata.md'
    #- 'Permalinks': 'extensions/permalinks.md'
    #- 'PyMdown': 'extensions/pymdown.md'
#  - 'Kontakt': 'kontakt.md'
#  - 'Impressum': 'impressum.md'
